WorkSearch/Controllers/UserCompaniesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WorkSearch.DBContext;
using WorkSearch.Models;
using System.Security.Claims;
using WorkSearch.ViewModels.UserCompanies;
using WorkSearch.Helpers.Messages;
using Microsoft.Win32;
using Microsoft.EntityFrameworkCore;
using WorkSearch.Helpers;

namespace WorkSearch.Controllers
{
    [Authorize]
    public class UserCompaniesController : MyBaseController
    {
        private readonly MyDBContext _dbContext;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public UserCompaniesController(MyDBContext dbContext, UserManager<User> userManager, IWebHostEnvironment hostingEnvironment)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                if (userId == null) throw new Exception(ErrorMessages.UserNotFound);

                var userCompanies = _dbContext.Companies.Where(c => c.UserId == int.Parse(userId)).ToList();

                var viewModel = new IndexViewModel { Companies = userCompanies };

                return View(viewModel);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateViewModel viewModel)
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                if (userId == null) throw new Exception(ErrorMessages.UserNotFound);

                string? photoName = FileHelper.SavePhoto(_hostingEnvironment, viewModel.Photo);

                viewModel.Company.PhotoUrl = photoName;
                viewModel.Company.UserId = int.Parse(userId);
                viewModel.Company.Id = Guid.NewGuid();

                _dbContext.Companies.Add(viewModel.Company);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                
                return RedirectToAction(Request.Headers["Referer"]);
            }
        }

        public IActionResult Edit(Guid id)
        {
            try
            {
                var company = _dbContext.Companies.First(c => c.Id == id);
                var viewModel = new EditViewModel { Company = company };

                return View(viewModel);
            }
             catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }

        [HttpPost]
        public IActionResult Edit(EditViewModel viewModel)
        {
            try
            {
                _dbContext.Companies.Update(viewModel.Company);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Details), new { id = viewModel.Company.Id});
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }

        }

        [HttpPost]
        public IActionResult Delete(Company company)
        {
            try
            {
                if(company.PhotoUrl != null) FileHelper.DeletePhoto(_hostingEnvironment, company.PhotoUrl);

                _dbContext.Companies.Remove(company);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }

        
        public IActionResult ChangePhoto(string id)
        {
            var viewModel = new ChangePhotoViewModel { Id = id};
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult ChangePhoto(ChangePhotoViewModel viewModel)
        {
            try
            {
                var photoName = FileHelper.SavePhoto(_hostingEnvironment, viewModel.Photo);

                if(photoName == null) return RedirectToAction(nameof(Index));

                var company = _dbContext.Companies.First(c => c.Id.ToString() == viewModel.Id);

                FileHelper.DeletePhoto(_hostingEnvironment, company.PhotoUrl);

                company.PhotoUrl = photoName;

                _dbContext.Companies.Update(company);

                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Details), new { id = viewModel.Id });
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }

        [HttpPost]
        public IActionResult DeletePhoto(string photoName, string id)
        {
            try
            {
                if (photoName != "no-photo.jpg")
                {
                    var company = _dbContext.Companies.First(c => c.Id.ToString() == id);

                    FileHelper.DeletePhoto(_hostingEnvironment, photoName);

                    company.PhotoUrl = null;

                    _dbContext.Companies.Update(company);
                    _dbContext.SaveChanges();
                }

                return TryRedirectBack();
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }

        public IActionResult Details(string id)
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                if (userId == null) throw new Exception(ErrorMessages.UserNotFound);

                var company = _dbContext.Companies.First(c => c.UserId == int.Parse(userId) && c.Id.ToString() == id);

                if(company == null) throw new Exception(ErrorMessages.CompanyNotFound);

                var viewModel = new DetailsViewModel { Company = company };

                return View(viewModel);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }
    }
}

WorkSearch/Controllers/UserSoleProprietorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WorkSearch.DBContext;
using WorkSearch.Helpers;
using WorkSearch.Helpers.Messages;
using WorkSearch.Models;
using WorkSearch.ViewModels.UserSoleProprietor;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace WorkSearch.Controllers
{
    [Authorize]
    public class UserSoleProprietorController : MyBaseController
    {
        private readonly MyDBContext _dbContext;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public UserSoleProprietorController(MyDBContext dbContext, UserManager<User> userManager, IWebHostEnvironment hostingEnvironment)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        
        public IActionResult Index()
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                if (userId == null) throw new Exception(ErrorMessages.UserNotFound);

                var SoleProprietor = _dbContext.SoleProprietors.Include(s => s.User).FirstOrDefault(s => s.UserId == int.Parse(userId));

                var viewModel = new IndexViewModel { SoleProprietor = SoleProprietor};

                return View(viewModel);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Edit(Guid id)
        {
            try
            {
                var soleProprietor = _dbContext.SoleProprietors.First(s => s.Id == id);
                var viewModel = new EditViewModel { SoleProprietor = soleProprietor };

                return View(viewModel);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }


        [HttpPost]
        public IActionResult Edit(EditViewModel viewModel)
        {
            try
            {
                _dbContext.SoleProprietors.Update(viewModel.SoleProprietor);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateViewModel viewModel)
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                if (userId == null) throw new Exception(ErrorMessages.UserNotFound);

                var user = _dbContext.Users.First(u => u.Id == int.Parse(userId));

                var photoName = FileHelper.SavePhoto(_hostingEnvironment, viewModel.Photo);

                viewModel.SoleProprietor.PhotoUrl = photoName;
                viewModel.SoleProprietor.Name = StringHelper.GetSoleProprietorName(user);
                viewModel.SoleProprietor.UserId = int.Parse(userId);

                _dbContext.SoleProprietors.Add(viewModel.SoleProprietor);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult ChangePhoto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangePhoto(ChangePhotoViewModel viewModel)
        {
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                if (userId == null) throw new Exception(ErrorMessages.UserNotFound);

                var photoName = FileHelper.SavePhoto(_hostingEnvironment, viewModel.Photo);
                if (photoName == null) return TryRedirectBack();

                var soleProprietor = _dbContext.SoleProprietors.First(c => c.UserId == int.Parse(userId));

                FileHelper.DeletePhoto(_hostingEnvironment, soleProprietor.PhotoUrl);

                soleProprietor.PhotoUrl = photoName;

                _dbContext.SoleProprietors.Update(soleProprietor);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }

        [HttpPost]
        public IActionResult DeletePhoto(string photoName, string id)
        {
            try
            {
                if (photoName != "no-photo.jpg")
                {
                    var soleProprietor = _dbContext.SoleProprietors.First(s => s.Id.ToString() == id);

                    FileHelper.DeletePhoto(_hostingEnvironment, photoName);

                    soleProprietor.PhotoUrl = null;

                    _dbContext.SoleProprietors.Update(soleProprietor);
                    _dbContext.SaveChanges();
                }

                return TryRedirectBack();
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;

                return TryRedirectBack();
            }
        }

        [HttpPost]
        public IActionResult Delete(SoleProprietor soleProprietor)
        {
            try
            {
                if (soleProprietor.PhotoUrl != null) FileHelper.DeletePhoto(_hostingEnvironment, soleProprietor.PhotoUrl);

                _dbContext.SoleProprietors.Remove(soleProprietor);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return TryRedirectBack();
            }
        }
    }
}

WorkSearch/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkSearch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkSearch.styles.css" asp-append-version="true" />
</head>
<body>
    @if (TempData["error"] != null)
    {
            <div class="alert">@TempData["error"]</div>
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkSearch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    @if(signInManager.IsSignedIn(User)){
                            <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserResumes" asp-action="Index">Мои резюме</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserCompanies" asp-action="Index">Мои компании</a>
                            </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserSoleProprietor" asp-action="Index">Моё ИП</a>
                                </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">Профиль</a>
                                    </li>
                        </ul>
                        <div>
                                <form asp-controller="Account" asp-action="Logout">
                                       <button type="submit" class="btn btn-danger">Logout</button>
                                </form>
                        </div>
                    }
                    else{
                         <div>
                                <a class="btn" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            <a class="btn" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WorkSearch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>